sudo: false
language: ruby
cache: bundler
before_install: gem install bundler
install: bundle install --jobs=3 --retry=3
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby-9.1.5.0
  - jruby-19mode
  - jruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head

